Repository Iduk-Baduk/itseats-web-customer, pull requests merged in 2025-06, with the labels that each got.

#5 [Feature] login UI
  src/App.jsx
  src/components/common/basic/Button.jsx
  src/components/common/basic/LineButton.jsx
  src/hooks/useLogin.js
  src/pages/Login.jsx
  src/pages/Login.module.css
Labels: feature

#4 [Feature] 회원가입 기능 구현
  package-lock.json
  package.json
  src/App.jsx
  src/components/RegistForm.jsx
  src/components/RegistForm.module.css
  src/components/common/basic/TextInput.jsx
  src/hooks/useRegistForm.js
  src/pages/Register.jsx
  src/pages/Register.module.css
  src/services/authAPI.js
Labels: feature

#12 [Feature] 홈화면 UI 구현
  public/icons/category/1인분.png
  public/icons/category/구이.png
  public/icons/category/도시락.png
  public/icons/category/돈가스.png
  public/icons/category/떡볶이.png
  public/icons/category/베트남쌀국수.png
  public/icons/category/보쌈.png
  public/icons/category/비빔밥.png
  public/icons/category/샌드위치.png
  public/icons/category/샐러드.png
  public/icons/category/순대국밥.png
  public/icons/category/스시.png
  public/icons/category/스파게티.png
  public/icons/category/야채죽.png
  public/icons/category/오징어회.png
  public/icons/category/종이가방.png
  public/icons/category/짜장면.png
  public/icons/category/치킨.png
  public/icons/category/커피.png
  public/icons/category/케이크.png
  public/icons/category/타코.png
  public/icons/category/피자.png
  public/icons/category/핫도그.png
  public/icons/category/햄버거.png
  public/icons/expand-more.svg
  public/icons/location/cancelIcon.svg
  public/icons/location/companyIcon.svg
  public/icons/location/gpsIcon.svg
  public/icons/location/homeIcon.svg
  public/icons/location/mapmarkerIcon.svg
  public/icons/location/pencilIcon.svg
  public/icons/location/searchIcon.svg
  public/samples/banner.jpg
  src/App.jsx
  src/components/animation/SlideInFromRight.jsx
  src/components/common/Header.jsx
  src/components/common/MenuGrid.jsx
  src/components/common/MenuGrid.module.css
  src/components/common/SearchInput.jsx
  src/components/common/SearchInput.module.css
  src/components/stores/StoreListItem.jsx
  src/components/stores/StoreListItem.module.css
  src/components/stores/Tabs.jsx
  src/components/stores/Tabs.module.css
  src/hooks/useAddressManager.js
  src/hooks/useRegistForm.js
  src/pages/Address.jsx
  src/pages/Address.module.css
  src/pages/AddressSearch.jsx
  src/pages/Home.jsx
  src/pages/Home.module.css
  src/pages/StackTest.jsx
  src/pages/stores/StoreDetail.jsx
  src/pages/stores/StoreList.jsx
  src/utils/categoryUtils.js
  src/variables.css
Labels: feature

#14 [Feature] 가게 목록 UI 구현
  src/components/stores/SortBottomSheet.jsx
  src/components/stores/SortBottomSheet.module.css
  src/components/stores/StoreListItem.jsx
  src/components/stores/StoreListItem.module.css
  src/components/stores/Tabs.jsx
  src/pages/Home.jsx
  src/pages/stores/StoreList.jsx
  src/pages/stores/StoreList.module.css
Labels: feature

#16 [🌎Feature] 검색 UI 구현
  src/App.jsx
  src/components/common/SearchHeaderBar.jsx
  src/components/common/SearchHeaderBar.module.css
  src/components/common/basic/FilterBar.jsx
  src/components/common/basic/FilterBar.module.css
  src/pages/Search.jsx
  src/pages/search/Search.jsx
  src/pages/search/Search.module.css
  src/pages/search/SearchResults.jsx
Labels: feature

#19 [Feature] 가게 상세 UI 구현
  package-lock.json
  package.json
  public/samples/food1.jpg
  public/samples/food2.jpg
  public/samples/food3.jpg
  src/App.jsx
  src/components/common/Header.jsx
  src/components/common/HeaderStoreDetail.jsx
  src/components/common/HeaderStoreDetail.module.css
  src/components/stores/AutoScrollTabs.jsx
  src/components/stores/AutoScrollTabs.module.css
  src/components/stores/DeliveryTypeTab.jsx
  src/components/stores/DeliveryTypeTab.module.css
  src/components/stores/MenuItem.jsx
  src/components/stores/MenuItem.module.css
  src/components/stores/PhotoSlider.jsx
  src/hooks/useShare.js
  src/pages/stores/MenuDetail.jsx
  src/pages/stores/MenuDetail.module.css
  src/pages/stores/StoreDetail.jsx
  src/pages/stores/StoreDetail.module.css
  src/variables.css
Labels: feature

#21 [Feature] 마이페이지 UI 구현
  public/icons/mypage/clipboard.svg
  public/icons/mypage/credit.svg
  public/icons/mypage/gift.svg
  public/icons/mypage/heart.svg
  public/icons/mypage/list.svg
  public/icons/mypage/megaphone.svg
  public/icons/mypage/message.svg
  public/icons/mypage/paper.svg
  public/icons/mypage/people.svg
  public/icons/mypage/percent.svg
  public/icons/mypage/question.svg
  public/icons/mypage/scooter.svg
  public/icons/mypage/settings.svg
  public/icons/mypage/sheild.svg
  public/icons/mypage/tag.svg
  src/App.jsx
  src/components/common/NavigationBar.jsx
  src/hooks/useMyPageDetails.js
  src/pages/MyPage.jsx
  src/pages/MyPage.module.css
  src/pages/MyPageDetails.jsx
  src/pages/MyPageDetails.module.css
  src/pages/address/Address.module.css
Labels: feature

#24 [Feature] 메뉴 상세 UI 구현
  src/components/common/BottomButton.jsx
  src/components/common/BottomButton.module.css
  src/components/stores/DeliveryTypeTab.jsx
  src/components/stores/MenuItem.jsx
  src/components/stores/OptionInput.jsx
  src/pages/Home.jsx
  src/pages/stores/MenuDetail.jsx
  src/pages/stores/StoreDetail.jsx
  src/variables.css
Labels: feature

#26 [Feature] 주문 내역 UI 구현
  src/components/orders/OrderCard.jsx
  src/components/orders/OrderCard.module.css
  src/components/orders/OrderSearch.jsx
  src/components/orders/OrderSearch.module.css
  src/components/orders/OrderTab.jsx
  src/components/orders/OrderTab.module.css
  src/pages/Order.jsx
  src/pages/Order.module.css
  src/variables.css
Labels: feature

#29 [Feature] 마이페이지 내부 중요 페이지 구현
  public/icons/banners/event1.jpg
  public/icons/banners/event2.jpg
  src/App.jsx
  src/hooks/useAppVersion.js
  src/hooks/useCoupons.js
  src/hooks/useEventList.js
  src/pages/Coupons.jsx
  src/pages/Coupons.module.css
  src/pages/Events.jsx
  src/pages/Events.module.css
  src/pages/EventsDetails.jsx
  src/pages/MyPage.jsx
  src/pages/Settings.jsx
  src/pages/Settings.module.css
Labels: feature

#30 [Feature] 장바구니 및 결제 UI 구현
  src/App.jsx
  src/components/common/BottomButton.jsx
  src/components/common/BottomButton.module.css
  src/components/common/basic/Button.module.css
  src/components/common/basic/LineButton.module.css
  src/components/common/basic/RadioButton.jsx
  src/components/common/basic/RadioButton.module.css
  src/components/common/basic/TextInput.jsx
  src/components/orders/cart/DeliveryRadioButton.jsx
  src/components/orders/cart/DeliveryRadioButton.module.css
  src/components/orders/cart/DeliveryToggle.jsx
  src/components/orders/cart/DeliveryToggle.module.css
  src/components/orders/cart/QuantityControl.jsx
  src/components/orders/cart/QuantityControl.module.css
  src/components/orders/cart/RiderRequestBottomSheet.jsx
  src/components/orders/cart/RiderRequestBottomSheet.module.css
  src/pages/Home.jsx
  src/pages/address/Address.module.css
  src/pages/orders/Cart.jsx
  src/pages/orders/Cart.module.css
  src/pages/search/Search.module.css
  src/pages/stores/MenuDetail.jsx
  src/pages/stores/MenuDetail.module.css
  src/variables.css
Labels: feature

#32 [Feature] #8 즐겨찾기 UI 구현
  public/samples/favoriteDefault.png
  src/App.jsx
  src/hooks/useFavorite.js
  src/pages/Favorite.jsx
  src/pages/Favorite.module.css
Labels: feature

#35 [Feature] #31 배달 현황 UI 구현
  public/icons/order/owner.jpg
  public/icons/order/rider.jpg
  src/App.jsx
  src/components/common/basic/LineButton.module.css
  src/components/orders/OrderCard.jsx
  src/components/orders/OrderCard.module.css
  src/components/orders/OrderProgress.jsx
  src/components/orders/OrderProgress.module.css
  src/components/orders/OrderTab.jsx
  src/pages/orders/Order.jsx
  src/pages/orders/Order.module.css
  src/pages/orders/OrderStatus.jsx
  src/pages/orders/OrderStatus.module.css
  src/variables.css
Labels: feature

#34 [Feature] #27 평가 및 리뷰 UI 구현
  src/App.jsx
  src/components/orders/OrderCard.module.css
  src/components/review/ReviewCard.jsx
  src/components/review/ReviewCard.module.css
  src/components/review/ReviewItem.jsx
  src/components/review/ReviewItem.module.css
  src/components/review/ReviewPhotoButton.jsx
  src/components/review/ReviewPhotoButton.module.css
  src/components/review/ReviewSubmitButton.jsx
  src/components/review/ReviewSubmitButton.module.css
  src/components/review/ReviewTextarea.jsx
  src/components/review/ReviewTextarea.module.css
  src/pages/Review.jsx
  src/pages/Review.module.css
  src/pages/address/AddressEdit.module.css
  src/pages/orders/Order.jsx
Labels: feature

#39 [Refactor]#37 리덕스 설정 및 셋업
  package-lock.json
  package.json
  src/App.jsx
  src/Root.jsx
  src/Store.js
  src/components/Counter.jsx
  src/main.jsx
  src/modules/counterModule.js
  src/modules/index.js
Labels: refactor

#47 [Feature] 매장 정보 UI 만들기 + 카카오맵 연동
  .gitignore
  index.html
  package.json
  src/App.jsx
  src/components/common/CommonMap.jsx
  src/components/stores/DeliveryTypeTab.jsx
  src/hooks/useShare.js
  src/pages/stores/StoreDetail.jsx
  src/pages/stores/StoreDetail.module.css
  src/pages/stores/StoreInfo.jsx
  src/pages/stores/StoreInfo.module.css
Labels: feature

#48 [Fix] 충돌 해결 중 누락된 Route 코드 추가
  src/Root.jsx
Labels: bug

#46 [Refactor] 결제관리 리팩토링
  db.json
  package-lock.json
  package.json
  src/Store.js
  src/components/common/Toast.jsx
  src/components/common/Toast.module.css
  src/hooks/usePaymentMethods.js
  src/modules/index.js
  src/pages/payments/AddAccount.jsx
  src/pages/payments/AddCard.jsx
  src/pages/payments/Payments.jsx
  src/store/index.js
  src/store/paymentSlice.js
  vite.config.js
Labels: feature

#49 [Refactor]#40 cart to redux
  package-lock.json
  package.json
  src/App.jsx
  src/Store.js
  src/components/common/BottomButton.jsx
  src/components/common/BottomButton.module.css
  src/components/orders/cart/QuantityControl.jsx
  src/modules/index.js
  src/pages/Home.jsx
  src/pages/orders/Cart.jsx
  src/pages/stores/MenuDetail.jsx
  src/store/cartSlice.js
  src/store/index.js
  src/store/localStorage.js
  src/utils/calculateCartTotal.js
  src/utils/hashUtils.js
Labels: feature

#53 Refactor/#45 order status to redux
  src/Root.jsx
  src/Store.js
  src/components/common/ErrorBoundary.jsx
  src/components/orders/OrderCard.jsx
  src/components/orders/OrderProgress.jsx
  src/constants/orderStatus.js
  src/hooks/useOrderStatus.js
  src/hooks/useOrderTestData.js
  src/modules/index.js
  src/pages/TestOrder.jsx
  src/pages/TestOrder.module.css
  src/pages/orders/Order.jsx
  src/pages/orders/OrderStatus.jsx
  src/store/index.js
  src/store/orderSlice.js
  src/utils/orderUtils.js
Labels: feature, refactor

#55 [Feature] coupon redux refactor
  src/components/common/Header.jsx
  src/components/orders/cart/CartAddressSection.jsx
  src/components/orders/cart/CartCouponSection.jsx
  src/components/orders/cart/CartDeliveryOptionSection.jsx
  src/components/orders/cart/CartMenuListSection.jsx
  src/components/orders/cart/CartPaymentSummarySection.jsx
  src/hooks/useCoupons.js
  src/modules/index.js
  src/pages/address/AddressEdit.jsx
  src/pages/address/AddressForm.jsx
  src/pages/coupons/Coupons.jsx
  src/pages/orders/Cart.jsx
  src/store/couponSlice.js
  src/store/index.js
Labels: feature

#58 Feature/#57 order api axios 적용
  src/Store.js
  src/components/common/ErrorBoundary.jsx
  src/config/api.js
  src/hooks/useOrderTracking.js
  src/pages/orders/Cart.jsx
  src/pages/orders/OrderStatus.jsx
  src/pages/payments/AddAccount.jsx
  src/pages/payments/AddCard.jsx
  src/pages/payments/Payments.jsx
  src/services/apiClient.js
  src/services/couponAPI.js
  src/services/index.js
  src/services/orderAPI.js
  src/services/paymentAPI.js
  src/store/couponSlice.js
  src/store/orderSlice.js
  src/store/paymentSlice.js
  src/utils/errorHandler.js
Labels: feature, refactor

#61 Refactor#60 order api structure
  .env.example
  .gitignore
  db.json
  src/App.jsx
  src/components/common/BottomButton.jsx
  src/components/common/BottomButton.module.css
  src/components/common/CommonMap.jsx
  src/components/common/DataMigrationNotice.jsx
  src/components/common/DataMigrationNotice.module.css
  src/pages/orders/Cart.jsx
  src/pages/stores/MenuDetail.jsx
  src/services/orderAPI.js
  src/services/paymentAPI.js
  src/store/cartSlice.js
  src/store/couponSlice.js
  src/store/paymentSlice.js
  src/utils/dataMigration.js
Labels: feature, refactor

#71 [Feature] 핵심 보안 및 UI 최적화 완료
  ..bfg-report/2025-06-26/23-53-40/cache-stats.txt
  ..bfg-report/2025-06-26/23-53-40/changed-files.txt
  ..bfg-report/2025-06-26/23-53-40/object-id-map.old-new.txt
  .env.example
  db.json
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/Root.jsx
  src/components/animation/SlideInFromRight.jsx
  src/components/animation/SlideInFromRight.module.css
  src/components/common/CommonMap.jsx
  src/components/common/DataMigrationNotice.module.css
  src/components/common/LoadingSpinner.jsx
  src/components/common/LoadingSpinner.module.css
  src/components/common/OptimizedImage.jsx
  src/components/common/OptimizedImage.module.css
  src/components/orders/cart/CartMenuListSection.jsx
  src/components/review/ReviewCard.module.css
  src/components/stores/MenuItem.jsx
  src/components/stores/PhotoSlider.jsx
  src/components/stores/StoreListItem.jsx
  src/index.css
  src/layouts/Layout.jsx
  src/main.jsx
  src/pages/Home.jsx
  src/pages/events/Events.jsx
  src/pages/orders/Cart.module.css
  src/pages/stores/StoreList.jsx
  src/styles/utilities.css
  src/utils/performance.js
  src/variables.css
  vite.config.js
Labels: enhancement, feature, refactor

#75 feat(ui-ux): 1단계 더미 데이터 제거 및 API 통합 완료
  src/config/api.js
  src/hooks/useFavorite.js
  src/hooks/useMyPageDetails.js
  src/hooks/useOrderStatus.js
  src/pages/coupons/Coupons.jsx
  src/pages/orders/Order.jsx
  src/pages/orders/Review.jsx
  src/pages/search/SearchResults.jsx
  src/pages/stores/StoreInfo.jsx
  src/pages/stores/StoreList.jsx
Labels: enhancement, feature, refactor

#76 [Feature] UI 상태 처리 통합 개선
  src/components/common/EmptyState.jsx
  src/components/common/EmptyState.module.css
  src/components/common/ErrorState.jsx
  src/components/common/ErrorState.module.css
  src/components/common/LoadingSpinner.jsx
  src/components/common/LoadingSpinner.module.css
  src/hooks/useUIState.js
  src/pages/Home.jsx
  src/pages/coupons/Coupons.jsx
  src/pages/orders/Cart.jsx
  src/pages/orders/Order.jsx
  src/pages/search/SearchResults.jsx
  src/pages/stores/StoreDetail.jsx
  src/pages/stores/StoreList.module.css
Labels: enhancement, feature, refactor

#77 [Refactor]#62 컴포넌트 개선 및 공통화 리팩토링
  src/components/common/Card.jsx
  src/components/common/Card.module.css
  src/components/common/ConfirmModal.jsx
  src/components/common/Modal.jsx
  src/components/common/Modal.module.css
  src/components/common/Tag.jsx
  src/components/common/Tag.module.css
  src/components/common/basic/Button.jsx
  src/components/common/basic/Button.module.css
  src/components/common/basic/LineButton.jsx
  src/components/orders/OrderCard.jsx
  src/components/orders/OrderCard.module.css
  src/components/review/ReviewSubmitButton.jsx
  src/pages/stores/MenuDetail.jsx
  src/store/cartSlice.js
  src/utils/dataMigration.js
Labels: enhancement, feature, refactor

#79 [Refactor]#62 4단계 쿠폰 UX 개선
  db.json
  src/components/orders/cart/CartCouponSection.jsx
  src/pages/coupons/Coupons.jsx
  src/pages/coupons/Coupons.module.css
  src/pages/orders/Cart.module.css
Labels: enhancement, feature, refactor

#80 [Chore]#62 5단계 전역 코드 품질 개선 및 정리
  src/App.jsx
  src/components/Counter.jsx
  src/hooks/useOrderTestData.js
  src/hooks/useOrderTracking.js
  src/hooks/useRegistForm.js
  src/pages/Home.jsx
  src/pages/orders/Cart.jsx
  src/pages/orders/OrderStatus.jsx
  src/pages/orders/Review.jsx
  src/pages/stores/MenuDetail.jsx
  src/store/couponSlice.js
  src/styles/utilities.css
  src/utils/dataMigration.js
Labels: enhancement, feature, refactor

#81 [Feature]#62 미구현 페이지들 및 완전한 결제 흐름 구현
  db.json
  docs/IMPLEMENTATION_STATUS.md
  src/Root.jsx
  src/components/RegistForm.jsx
  src/components/common/Toast.module.css
  src/components/orders/OrderCard.jsx
  src/components/orders/OrderCard.module.css
  src/components/orders/OrderProgressSteps.jsx
  src/components/orders/OrderProgressSteps.module.css
  src/hooks/useOrderStatus.js
  src/hooks/useOrderTestData.js
  src/hooks/useRegistForm.js
  src/pages/Favorite.module.css
  src/pages/Login.jsx
  src/pages/NotFound.jsx
  src/pages/NotFound.module.css
  src/pages/coupons/CouponHistory.jsx
  src/pages/coupons/CouponHistory.module.css
  src/pages/coupons/Coupons.jsx
  src/pages/mypage/MyPage.jsx
  src/pages/orders/Cart.jsx
  src/pages/orders/Order.jsx
  src/pages/orders/OrderStatus.jsx
  src/pages/orders/OrderStatus.module.css
  src/pages/payments/AddPaymentMethod.jsx
  src/pages/payments/PaymentFailure.jsx
  src/pages/payments/PaymentFailure.module.css
  src/pages/payments/PaymentSuccess.jsx
  src/pages/payments/PaymentSuccess.module.css
  src/pages/stores/MenuDetail.jsx
  src/pages/stores/StoreDetail.jsx
  src/services/authAPI.js
Labels: enhancement, feature, refactor

#84 [Feature] #82 마이페이지 상세 기능 구현 및 데이터 연동
  PR_TEMPLATE.md
  db.json
  src/hooks/useCurrentUser.js
  src/hooks/useFavorite.js
  src/hooks/useLogin.js
  src/hooks/useMyPageDetails.js
  src/hooks/useOrderTestData.js
  src/pages/Favorite.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/TestOrder.jsx
  src/pages/TestOrder.module.css
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/MyPageDetails.jsx
  src/pages/mypage/MyPageDetails.module.css
  src/services/authAPI.js
  src/services/index.js
  src/services/userAPI.js
  src/store/orderSlice.js
  src/utils/logger.js
  src/utils/testDataInitializer.js
Labels: enhancement, feature

#85 Fix/export error hotfix and enhancement UI
  src/Store.js
  src/components/RegistForm.jsx
  src/components/RegistForm.module.css
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/Login.module.css
  src/store/orderSlice.js
Labels: bug

#88 Qa/#87 pre api integration
  db.json
  src/App.jsx
  src/components/common/Toast.jsx
  src/components/orders/OrderCard.jsx
  src/components/orders/OrderProgress.jsx
  src/components/orders/OrderProgress.module.css
  src/components/orders/OrderProgressSteps.jsx
  src/components/orders/OrderProgressSteps.module.css
  src/components/orders/cart/CartAddressSection.jsx
  src/components/orders/cart/CartPaymentMethodSection.jsx
  src/components/orders/cart/CartPaymentSummarySection.jsx
  src/config/development.js
  src/hooks/useCurrentUser.js
  src/hooks/useFavorite.js
  src/hooks/useMyPageDetails.js
  src/hooks/useOrderStatus.js
  src/hooks/useOrderTestData.js
  src/hooks/useOrderTracking.js
  src/pages/Favorite.jsx
  src/pages/TestOrder.jsx
  src/pages/TestOrder.module.css
  src/pages/mypage/MyPageDetails.jsx
  src/pages/orders/Cart.jsx
  src/pages/orders/Cart.module.css
  src/pages/orders/Order.jsx
  src/pages/orders/OrderStatus.jsx
  src/pages/orders/OrderStatus.module.css
  src/pages/payments/AddAccount.jsx
  src/pages/payments/AddCard.jsx
  src/pages/payments/PaymentSuccess.jsx
  src/pages/payments/PaymentSuccess.module.css
  src/pages/stores/MenuDetail.jsx
  src/pages/stores/StoreDetail.jsx
  src/services/orderAPI.js
  src/services/userAPI.js
  src/store/orderSlice.js
  src/utils/orderUtils.js
  src/utils/storageUtils.js
  src/variables.css
Labels: enhancement, feature
