Repository Iduk-Baduk/itseats-web-customer, pull requests merged in 2025-07, with the labels that each got.

#94 [Feature] 주소 추가 API 연동
  src/hooks/useAddressRedux.js
  src/pages/address/AddressCurrentLocation.jsx
  src/pages/address/AddressEdit.module.css
  src/pages/address/AddressForm.jsx
  src/pages/address/AddressNew.jsx
  src/services/addressAPI.js
  src/store/addressSlice.js
Labels: feature

#100 [Feature] 주소 관리 API 연동
  src/hooks/useAddressRedux.js
  src/pages/address/Address.jsx
  src/pages/address/AddressEdit.jsx
  src/pages/address/AddressNew.jsx
  src/services/addressAPI.js
  src/store/addressSlice.js
Labels: feature

#103 [Feature] 가게 목록 조회 API 연동
  db.json
  src/Root.jsx
  src/components/orders/cart/RiderRequestBottomSheet.module.css
  src/components/stores/SortBottomSheet.jsx
  src/components/stores/SortBottomSheet.module.css
  src/components/stores/StoreListItem.jsx
  src/components/stores/Tabs.module.css
  src/config/api.js
  src/hooks/useFavorite.js
  src/hooks/useMyPageDetails.js
  src/pages/Favorite.jsx
  src/pages/Home.jsx
  src/pages/orders/Cart.jsx
  src/pages/search/SearchResults.jsx
  src/pages/stores/StoreDetail.jsx
  src/pages/stores/StoreList.jsx
  src/services/storeAPI.js
  src/store/storeSlice.js
  src/utils/storeUtils.js
Labels: feature

#105 [Feature] 메뉴 조회 API 연동
  db.json
  src/components/common/Header.module.css
  src/components/stores/AutoScrollTabs.jsx
  src/components/stores/HeaderMenuDetail.module.css
  src/components/stores/HeaderStoreDetail.module.css
  src/components/stores/MenuItem.jsx
  src/hooks/useFavorite.js
  src/pages/orders/Cart.jsx
  src/pages/stores/MenuDetail.jsx
  src/pages/stores/StoreDetail.jsx
  src/services/storeAPI.js
  src/store/storeSlice.js
  src/utils/storeUtils.js
Labels: feature

#112 [Feature] #106-toss-api-v3
  PR_TOSS_PAYMENT_INTEGRATION.md
  README.md
  docs/ENVIRONMENT_SETUP.md
  docs/IMPLEMENTATION_STATUS.md
  package-lock.json
  package.json
  src/Root.jsx
  src/components/common/ApiErrorHandler.jsx
  src/components/common/ApiErrorHandler.module.css
  src/components/orders/cart/CartPaymentMethodSection.jsx
  src/components/payment/TossPaymentWidget.jsx
  src/index.css
  src/pages/orders/Cart.jsx
  src/pages/orders/Cart.module.css
  src/pages/orders/OrderStatus.jsx
  src/pages/orders/OrderStatus.module.css
  src/pages/payments/PaymentFailure.jsx
  src/pages/payments/PaymentFailure.module.css
  src/pages/payments/PaymentSuccess.jsx
  src/pages/payments/PaymentSuccess.module.css
  src/pages/payments/TossPaymentSuccess.jsx
  src/services/apiClient.js
  src/services/index.js
  src/services/orderAPI.js
  src/services/tossPaymentAPI.js
  src/styles/CommonResult.module.css
  src/styles/buttonUtils.css
  src/utils/apiRetry.js
Labels: feature

#123 [Chore] 빌드 및 버킷 업로드 설정
  .github/workflows/deploy.yml
Labels: chore

#125 [Fix] counter export 관련 빌드 문제 수정
  src/modules/counterModule.js
Labels: bug

#127 [Release] 2025-07-13 00:47
  src/modules/counterModule.js
Labels: release

#119 [Feature] 리뷰 작성 API 연동
  package-lock.json
  src/Root.jsx
  src/components/orders/OrderCard.jsx
  src/components/review/ReviewItem.jsx
  src/config/api.js
  src/hooks/useSubmitReview.js
  src/pages/orders/Order.jsx
  src/pages/orders/Review.jsx
  src/pages/orders/ReviewView.jsx
  src/services/reviewAPI.js
Labels: feature

#121 [Feature] 쿠폰 발급 및 쿠폰 조회 연동
  package-lock.json
  package.json
  public/samples/coupon-page-banner.jpg
  src/Root.jsx
  src/components/common/CouponBanner.jsx
  src/components/common/CouponBanner.module.css
  src/components/common/MainBannerSlider.jsx
  src/components/common/MainBannerSlider.module.css
  src/config/api.js
  src/pages/Home.jsx
  src/pages/coupons/Coupons.jsx
  src/pages/coupons/Coupons.module.css
  src/pages/coupons/MyCoupons.jsx
  src/pages/coupons/MyCoupons.module.css
  src/pages/mypage/MyPage.jsx
  src/services/couponAPI.js
  src/utils/couponUtils.js
Labels: feature

#133 [Feature] 리뷰 관련 연동
  src/Root.jsx
  src/config/api.js
  src/hooks/useMyPageDetails.js
  src/pages/mypage/MyPageDetails.jsx
  src/pages/mypage/MyPageDetails.module.css
  src/pages/orders/Order.jsx
  src/pages/stores/ReviewListPage.jsx
  src/pages/stores/ReviewListPage.module.css
  src/pages/stores/StoreDetail.jsx
  src/services/reviewAPI.js
  src/services/storeAPI.js
Labels: feature

#138 [Refactor] 가게 목록 조회 및 검색 결과 무한 스크롤 적용
  src/components/stores/StoreListItem.jsx
  src/pages/search/Search.jsx
  src/pages/search/SearchResults.jsx
  src/pages/stores/StoreInfo.jsx
  src/pages/stores/StoreList.jsx
  src/services/storeAPI.js
  src/store/storeSlice.js
Labels: refactor

#139 [Fix] 빌드 오류 사항 수정
  src/config/api.js
  src/services/reviewAPI.js
Labels: bug

#140 [Release] 2025-07-14 11:49
  src/Root.jsx
  src/components/stores/StoreListItem.jsx
  src/config/api.js
  src/hooks/useMyPageDetails.js
  src/pages/mypage/MyPageDetails.jsx
  src/pages/mypage/MyPageDetails.module.css
  src/pages/orders/Order.jsx
  src/pages/search/Search.jsx
  src/pages/search/SearchResults.jsx
  src/pages/stores/ReviewListPage.jsx
  src/pages/stores/ReviewListPage.module.css
  src/pages/stores/StoreDetail.jsx
  src/pages/stores/StoreInfo.jsx
  src/pages/stores/StoreList.jsx
  src/services/reviewAPI.js
  src/services/storeAPI.js
  src/services/tossPaymentAPI.js
  src/store/storeSlice.js
Labels: release

#141 [Chore] 내 쿠폰 아이콘 추가
  public/icons/mypage/coupon.svg
  src/pages/mypage/MyPage.jsx
Labels: chore

#145 fix: 가게 사진 연동
  src/components/review/ReviewCard.jsx
  src/components/review/ReviewCard.module.css
  src/components/review/ReviewItem.jsx
  src/components/review/ReviewItem.module.css
  src/pages/orders/Review.jsx
Labels: refactor

#148 [Release] 2025-07-15 02:55
  public/icons/logos/toss.png
  src/components/common/MenuGrid.module.css
  src/components/review/ReviewCard.jsx
  src/components/review/ReviewCard.module.css
  src/components/review/ReviewItem.jsx
  src/components/review/ReviewItem.module.css
  src/pages/orders/Review.jsx
  src/pages/payments/TossPaymentSuccess.jsx
Labels: release

#149 [Release] 2025-07-15 10:30
  src/hooks/useRegistForm.js
Labels: release

#150 [Release] 2025-07-16 20:42
  .github/workflows/deploy.yml
Labels: release
